services:
  geac-postgres:
    container_name: geac-postgres
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
      - postgres-data:/var/lib/postgresql
    networks:
      - app-private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ## O serviço do backend foi temporariamente comentado para focar na configuração do banco de dados. --- IGNORE ---
  # backend:
  #   container_name: spring-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://geac-postgres:5432/postgres
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #   depends_on:
  #     geac-postgres:
  #       condition: service_healthy
  #   networks:
  #     - app-private-network

volumes:
  postgres-data:

networks:
  app-private-network:
    driver: bridge
    name: app-private-network